backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["Hydroponics","Lakadong","Microgreens"]}
      - {label: "Author", name: "author", widget: "string", default: "Seechur Agro — Editorial Team"}
      - {label: "Cover Image", name: "image", widget: "image", choose_url: true}
      - {label: "Summary", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
